services:
  db:
    image: postgres:16-alpine
    container_name: pharmatrack-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-pharmatrack}
      POSTGRES_USER: ${POSTGRES_USER:-pharmatrack}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-pharmatrack}
    ports:
      - "5432:5432"
    volumes:
      - pharmatrack_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-pharmatrack} -d ${POSTGRES_DB:-pharmatrack}"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build:
      context: ./backend
    container_name: pharmatrack-backend
    environment:
      DB_URL: jdbc:postgresql://db:5432/${POSTGRES_DB:-pharmatrack}
      DB_USERNAME: ${POSTGRES_USER:-pharmatrack}
      DB_PASSWORD: ${POSTGRES_PASSWORD:-pharmatrack}
      CORS_ALLOWED_ORIGINS: http://localhost:4200
      JWT_SECRET: ${JWT_SECRET:-U2VjdXJlLURldi9Qcm9kLUtleS1DaGFuZ2UtTWUtNjQrQnl0ZXMtU3VwZXItTG9uZy1Gb3ItSFMyNTZBLUhlYWx0aC1GdW5jdGlvbg==}
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
    container_name: pharmatrack-frontend
    command: nginx -g "daemon off;"
    ports:
      - "4200:80"
    depends_on:
      - backend

volumes:
  pharmatrack_pgdata:
